import { createClient } from "npm:@supabase/supabase-js@2.111.0";

const ADMIN_EMAIL=(Deno.env.get("ADMIN_EMAIL")||"").toLowerCase();
const MASTER_ROSTER_FROM="2026-08-24";
const MANAGER_ROSTER_FROM="2026-09-07";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Cache-Control":"no-store"};
const admin=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",{auth:{persistSession:false,autoRefreshToken:false}});
const clone=(v:any)=>JSON.parse(JSON.stringify(v));
const nm=(v:any)=>{const s=String(v||"").trim();return s==="Аслан"?"Асик":s;};
const same=(a:any,b:any)=>nm(a).toLocaleLowerCase("ru")===nm(b).toLocaleLowerCase("ru");
const reply=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"Content-Type":"application/json"}});
function validDate(v:any){const s=String(v||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const [y,m,d]=s.split("-").map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d;}
async function owner(req:Request){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const {data,error}=await admin.auth.getUser(token);if(error||!data.user)return null;return String(data.user.email||"").toLowerCase()===ADMIN_EMAIL?data.user:null;}
async function cfg(){const {data,error}=await admin.from("ma_schedule_config").select("settings,updated_at").eq("id","main").maybeSingle();if(error)throw error;if(!data?.settings)throw new Error("Общий график не найден");return {raw:clone(data.settings),updatedAt:String(data.updated_at||"")};}
function svc(raw:any,v:any){const s1=String(raw.service1||"Моба"),s2=String(raw.service2||"Нова"),q=String(v||"").trim();if(q==="s1"||same(q,s1))return {key:"s1",name:s1};if(q==="s2"||same(q,s2))return {key:"s2",name:s2};throw new Error("Неизвестная точка");}
function active(raw:any,date:string){const a=(Array.isArray(raw.employeeSchedules)?raw.employeeSchedules:[]).filter((x:any)=>x?.name&&["manager","master"].includes(String(x.role))).map((x:any)=>({name:nm(x.name),role:x.role==="master"?"master":"manager",inactive:false}));const changes=(Array.isArray(raw.staffChanges)?raw.staffChanges:[]).filter((x:any)=>x?.oldName&&validDate(x.date)&&String(x.date)<=date).slice().sort((x:any,y:any)=>String(x.date).localeCompare(String(y.date)));for(const ch of changes)for(const e of a){if(!same(e.name,ch.oldName))continue;const n=nm(ch.newName);if(ch.type==="left"||!n)e.inactive=true;else{e.name=n;e.inactive=false;}}for(const e of a){if(date>=MASTER_ROSTER_FROM&&e.role==="master"&&same(e.name,"Ислам"))e.inactive=true;if(date>=MANAGER_ROSTER_FROM&&e.role==="manager"&&same(e.name,"Сергей"))e.inactive=true;}return a.filter((e:any,i:number,arr:any[])=>!e.inactive&&arr.findIndex(x=>x.role===e.role&&same(x.name,e.name))===i);}
function target(raw:any,date:string,s:any,v:any){const people=active(raw,date),m0=nm(v?.manager),w0=nm(v?.master);if(!m0||!w0)throw new Error("Нужно передать target.manager и target.master");const canon=(x:string)=>people.find((p:any)=>same(p.name,x))?.name||x,manager=m0==="Без менеджера"?m0:canon(m0),master=w0==="Без мастера"?w0:canon(w0);if(manager!=="Без менеджера"){const e=people.find((p:any)=>same(p.name,manager));const responsible=s.key==="s2"&&same(manager,master)&&e?.role==="master";if(!e||e.role!=="manager"&&!responsible)throw new Error("Недопустимый менеджер");}if(master!=="Без мастера"){const e=people.find((p:any)=>same(p.name,master));if(!e||e.role!=="master")throw new Error("Недопустимый мастер");}return {manager,master};}
function before(v:any){const manager=nm(v?.manager),master=nm(v?.master);if(!manager||!master)throw new Error("Передай expectedCurrent из read-API");return {manager,master};}
function next(raw:any,date:string,s:any,b:any,a:any,reason:string){const n=clone(raw),rows=Array.isArray(n.dayOverrides)?n.dayOverrides:[];n.dayOverrides=rows.filter((r:any)=>!(String(r.date||"")===date&&(String(r.serviceKey||"")===s.key||same(r.service,s.name))));const mc=!same(b.manager,a.manager),wc=!same(b.master,a.master);n.dayOverrides.push({id:`chatgpt-${Date.now()}-${crypto.randomUUID().slice(0,8)}`,date,serviceKey:s.key,service:s.name,manager:a.manager,master:a.master,reason:reason.slice(0,250),replacedRole:mc&&!wc?"manager":wc&&!mc?"master":"",replacedName:mc&&!wc?b.manager:wc&&!mc?b.master:""});return n;}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return reply({ok:false,error:"POST required"},405);const user=await owner(req);if(!user)return reply({ok:false,error:"Требуется вход владельца"},401);try{const body=await req.json().catch(()=>({})),current=await cfg(),date=String(body.date||"");if(!validDate(date))throw new Error("date должна быть YYYY-MM-DD");if(String(body.expectedConfigUpdatedAt||"")!==current.updatedAt){const e:any=new Error("График изменился после чтения");e.status=409;throw e;}const s=svc(current.raw,body.service),b=before(body.expectedCurrent),a=target(current.raw,date,s,body.target),reason=String(body.reason||"Изменение через ChatGPT");const path=new URL(req.url).pathname;if(path.endsWith("/preview-change"))return reply({ok:true,mode:"preview",configUpdatedAt:current.updatedAt,date,service:s.name,before:b,after:a,requiresConfirm:true});if(!path.endsWith("/apply-change"))return reply({ok:false,error:"Неизвестный маршрут"},404);if(body.confirm!==true)return reply({ok:false,error:"confirm должен быть true"},400);const settings=next(current.raw,date,s,b,a,reason),now=new Date().toISOString();const {data,error}=await admin.from("ma_schedule_config").update({settings,updated_at:now}).eq("id","main").eq("updated_at",current.updatedAt).select("updated_at").maybeSingle();if(error)throw error;if(!data?.updated_at){const e:any=new Error("Конфликт изменения");e.status=409;throw e;}const audit=await admin.from("ma_grafik_api_audit").insert({actor_email:user.email||ADMIN_EMAIL,action:"apply_change",status:"applied",work_date:date,service:s.name,before_pair:b,after_pair:a,config_before_updated_at:current.updatedAt,config_after_updated_at:data.updated_at,previous_settings:current.raw});if(audit.error)console.error(audit.error);return reply({ok:true,applied:true,updatedAt:data.updated_at,auditStored:!audit.error,dayOverride:{date,service:s.name,...a,reason}});}catch(e:any){return reply({ok:false,error:e?.message||"Ошибка API"},Number(e?.status)||400);}});
