(function(global){
  "use strict";
  if(typeof document==="undefined"||typeof window==="undefined")return;
  if(global.__maOwnerAssistantStarted)return;
  global.__maOwnerAssistantStarted=true;
  const SUPABASE_URL="https://yedzfmibceboncrytbqz.supabase.co",PUBLISHABLE_KEY="sb_publishable_tSqbw3aeAgxYuzHhQurCuw_yDze4ZNn",AUTH_KEY="ma_schedule_admin_session_v1";
  const READ_API=`${SUPABASE_URL}/functions/v1/ma-grafik-api`,ATT_API=`${SUPABASE_URL}/functions/v1/ma-grafik-attendance-api`,core=global.MAAssistantCore;
  let busy=false;
  const ctx={lastIntent:"",lastEmployee:"",lastDate:"",lastRange:"",lastLocation:""};
  function n(v){return core?.normalizeText?core.normalizeText(v):String(v||"").toLowerCase().trim();}
  function intent(text){const t=n(text);if(/(что.*сегодня.*не так|есть.*(проблем|наруш)|все нормально сегодня|что требует внимания|проверь сегодняшний день|проверь сотрудников|как дела на точках|что по работе|что там сегодня|как мои работают)/.test(t))return"attention";if(/(как начался день|как открылись|все открылись|кто открылся|кто опоздал утром|как открылись точки)/.test(t))return"morning";if(/(как прошел день|итог дня|как сегодня отработали|итоги по сотрудникам)/.test(t))return"daySummary";if(/(мне нужно вмешаться|покажи только важное|есть что-то важное)/.test(t))return"important";if(/(проверь.*график|ошибки.*график|все нормально с графиком)/.test(t))return"scheduleAudit";if(/(статистика|дисциплина|опоздания).*(олег|георг|асик|арсен)|(олег|георг|асик|арсен).*(за месяц|за неделю|как работает)/.test(t))return"employee";return"";}
  function session(){try{const x=JSON.parse(localStorage.getItem(AUTH_KEY)||"null");return x?.access_token?x:null;}catch(_){return null;}}
  async function refresh(){const s=session();if(!s?.refresh_token)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{"Content-Type":"application/json",apikey:PUBLISHABLE_KEY},body:JSON.stringify({refresh_token:s.refresh_token})});const d=await r.json().catch(()=>null);if(!r.ok||!d?.access_token)return null;const x={...s,...d};localStorage.setItem(AUTH_KEY,JSON.stringify(x));return x;}
  async function get(url){let s=session();if(!s)throw new Error("AUTH");let r=await fetch(url,{headers:{Authorization:`Bearer ${s.access_token}`}});if(r.status===401){s=await refresh();if(!s)throw new Error("AUTH");r=await fetch(url,{headers:{Authorization:`Bearer ${s.access_token}`}});}const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error("READ");return d;}
  function add(role,text){const b=document.getElementById("maAssistantMessages");if(!b)return;const m=document.createElement("div");m.className=`ma-msg ${role}`;m.textContent=String(text||"");b.appendChild(m);b.scrollTop=b.scrollHeight;}
  function today(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Moscow",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),o={};p.forEach(x=>{if(x.type!=="literal")o[x.type]=x.value;});return`${o.year}-${o.month}-${o.day}`;}
  function dateRange(text){const base=today();const r=core?.parseRange?.(text,base);return r?.from&&r?.to?r:{from:base,to:base};}
  function attendanceQuery(q){const u=new URL(ATT_API);u.searchParams.set("q",q);return get(u);}
  function schedule(from,to){const u=new URL(`${READ_API}/schedule`);u.searchParams.set("from",from);u.searchParams.set("to",to);return get(u);}
  function oneWarning(raw){let text=String(raw||"Нет данных.").trim();text=text.replace(/\n*Важно:\s*(?:это\s+)?время открытия смены[^\n]*/gi,"").replace(/\n*Важно:\s*время открытия смены[^\n]*/gi,"").trim();return `${text}\n\nВажно: это время открытия смены в приложении, а не подтверждение фактического прихода сотрудника.`;}
  async function answer(type,text){if(type==="attention"||type==="important"||type==="morning"){const q=type==="morning"?"кто сегодня опоздал и как открылись смены":"кто сегодня опоздал";const d=await attendanceQuery(q);const raw=String(d.answer||"Нет данных.");if(type==="important"&&/нет (опоздан|наруш)|вовремя/i.test(raw))return"Нет. По доступным данным сейчас вмешательство не требуется.";return oneWarning(raw);}
    if(type==="daySummary"){const d=await attendanceQuery("итог смен сегодня: открытия, закрытия и опоздания");return oneWarning(d.answer||"Нет данных за сегодня.");}
    if(type==="employee"){const r=dateRange(text),s=await schedule(r.from,r.to);const names=[];for(const day of s.days||[])for(const pair of Object.values(day.services||{}))for(const x of[pair?.manager,pair?.master])if(x)names.push(String(x));const mentioned=core?.findMentionedEmployees?.(text,[...new Set(names)])||[];const name=mentioned[0]?.name;if(!name)return"Укажи сотрудника, например: «Статистика Олега за месяц».";ctx.lastEmployee=name;const a=await attendanceQuery(`опоздания ${name} ${/недел/.test(n(text))?"за неделю":"за месяц"}`);return`${name}\n${String(a.answer||"Нет достаточных фактических данных.")}\n\nОтсутствие записи смены не считается прогулом автоматически.`;}
    if(type==="scheduleAudit"){const r=dateRange(text),d=await schedule(r.from,r.to),issues=[];for(const day of d.days||[])for(const[service,p]of Object.entries(day.services||{})){if(!p?.manager||/не назначен/i.test(String(p.manager)))issues.push(`${day.date} · ${service}: не назначен менеджер.`);if(!p?.master||/не назначен/i.test(String(p.master)))issues.push(`${day.date} · ${service}: не назначен мастер.`);}return issues.length?`Требуют внимания ${issues.length}:\n• ${issues.slice(0,8).join("\n• ")}`:"По заданным в приложении назначениям явных пропусков не найдено.";}
    return"Не понял команду.";
  }
  async function handle(type,text){if(busy)return;busy=true;add("user",text);try{ctx.lastIntent=type;const out=await answer(type,text);add("assistant",out);}catch(e){console.error("MA Assistant owner",e);add("error","Не удалось выполнить проверку. Попробуй ещё раз.");}finally{busy=false;}}
  function intercept(text,event){const clean=String(text||"").trim(),type=intent(clean);if(!type)return false;event?.preventDefault?.();event?.stopImmediatePropagation?.();const input=document.getElementById("maAssistantInput");if(input)input.value="";handle(type,clean);return true;}
  document.addEventListener("click",e=>{const q=e.target?.closest?.(".ma-assistant-examples [data-text]");if(q&&intercept(q.dataset.text||q.textContent||"",e))return;const send=e.target?.closest?.("#maAssistantSend");if(send){const input=document.getElementById("maAssistantInput");intercept(input?.value||"",e);}},true);
  document.addEventListener("keydown",e=>{if(e.target?.id==="maAssistantInput"&&e.key==="Enter"&&!e.shiftKey)intercept(e.target.value||"",e);},true);
})(typeof window!=="undefined"?window:globalThis);
