(()=>{
  "use strict";
  const BASE_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-api";
  const PHASE_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-phase1-api";
  const FINAL_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-final-api";
  const API_KEY="sb_publishable_tSqbw3aeAgxYuzHhQurCuw_yDze4ZNn",ADMIN_SESSION_KEY="ma_schedule_admin_session_v1",CRM_SESSION_KEY="ma_crm_session_v1";
  const chainedFetch=window.fetch.bind(window),state={actor:null,currentRepairId:"",renderSeq:0,payrollMounted:false};
  const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0;},money=v=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(num(v))+" ₽";
  function readJson(k){try{return JSON.parse(localStorage.getItem(k)||"null");}catch(_){return null;}}function headers(){const h={"Content-Type":"application/json","apikey":API_KEY},a=readJson(ADMIN_SESSION_KEY)?.access_token,s=localStorage.getItem(CRM_SESSION_KEY)||"";if(a)h.Authorization=`Bearer ${a}`;if(s)h["x-crm-session"]=s;return h;}
  function toast(msg){const root=$("crmToast");if(!root)return;root.textContent=String(msg||"");root.classList.add("show");setTimeout(()=>root.classList.remove("show"),2800);}
  async function api(url,op,payload={}){const r=await chainedFetch(url,{method:"POST",headers:headers(),body:JSON.stringify({op,...payload}),cache:"no-store"}),d=await r.json().catch(()=>({ok:false,error:"Некорректный ответ сервера"}));if(!r.ok||d?.ok===false)throw new Error(d?.error||`Ошибка ${r.status}`);return d;}
  function role(){return state.actor?.role|| (state.actor?.kind==="admin"?"admin":"");}
  function applyRoleUi(){const r=role();document.body.dataset.crmRole=r||"";if($("crmUserRole"))$("crmUserRole").textContent=r==="admin"?"Владелец / администратор":r==="master"?"Мастер":"Менеджер";const hide=(sel,on)=>document.querySelectorAll(sel).forEach(x=>x.classList.toggle("hidden",!!on));hide('[data-view="payments"]',r!=="admin");hide('[data-view="clients"],[data-view="sales"],[data-view="inventory"],[data-view="reports"]',r==="master");hide("#globalNewRepair,#mobileNewRepair",r==="master");if(r==="master"&&document.querySelector('[data-view-panel="dashboard"]:not(.hidden)'))document.querySelector('[data-view="orders"]')?.click();mountPayroll();}
  window.fetch=async function(input,init={}){const url=typeof input==="string"?input:input?.url||"";let body=null;try{if(init?.body)body=JSON.parse(String(init.body));}catch(_){ }
    if(url.startsWith(BASE_API)&&body?.op==="list-sales"&&role()==="master")return new Response(JSON.stringify({ok:true,sales:[]}),{status:200,headers:{"Content-Type":"application/json"}});
    const response=await chainedFetch(input,init);
    if(url.startsWith(BASE_API)&&body?.op==="bootstrap"&&response.ok){try{const d=await response.clone().json();state.actor=d?.actor||null;setTimeout(applyRoleUi,0);}catch(_){ }}
    if(url.startsWith(BASE_API)&&body?.op==="repair"&&body?.id){state.currentRepairId=String(body.id);setTimeout(()=>renderRepairTools(state.currentRepairId),60);}
    return response;
  };
  function sizeText(bytes){const n=num(bytes);return n<1024?`${n} Б`:n<1048576?`${(n/1024).toFixed(1)} КБ`:`${(n/1048576).toFixed(1)} МБ`;}
  function fileRows(files=[]){if(!files.length)return'<div class="final-help">Фото и файлов пока нет.</div>';return files.map(f=>`<div class="final-file"><div><b>${esc(f.file_name)}</b><small>${esc(sizeText(f.size_bytes))} · ${esc(f.uploaded_by||"")}</small></div><div class="final-file-actions">${f.url?`<a href="${esc(f.url)}" target="_blank" rel="noopener">Открыть</a>`:""}${role()!=="master"?`<button type="button" data-final-delete-file="${esc(f.id)}">Удалить</button>`:""}</div></div>`).join("");}
  function toolHtml(d){const r=d.repair||{},until=r.warranty_until?new Date(r.warranty_until):null,active=!!until&&until>=new Date();return `<div id="crmFinalTools" class="detail-panel crm-final-panel"><div class="final-title-row"><div><h3>Документы, файлы и связь с клиентом</h3><p>Финальный рабочий блок заказа</p></div>${r.warranty_case?'<span class="final-warranty-badge">Гарантийный заказ</span>':active?'<span class="final-warranty-badge active">Гарантия активна</span>':'<span class="final-warranty-badge">Гарантия не активна</span>'}</div><div class="final-actions"><button class="final-action-btn" id="finalPrint" type="button">Печать квитанции</button><button class="final-action-btn" id="finalWhatsApp" type="button">Написать в WhatsApp</button><label class="final-action-btn" style="cursor:pointer">+ Фото / файл<input id="finalFileInput" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf" hidden></label>${d.canCreateWarranty?'<button class="final-action-btn primary" id="finalWarranty" type="button">Гарантийное обращение</button>':""}</div><div class="final-files" id="finalFiles">${fileRows(d.files||[])}</div><div class="final-help">Файлы хранятся в закрытом хранилище CRM. WhatsApp открывается с уже подготовленным сообщением — отправку подтверждаешь сам.</div></div>`;}
  async function renderRepairTools(id){const body=$("repairDetailBody");if(!body||!id)return;const seq=++state.renderSeq;try{const d=await api(FINAL_API,"repair-tools",{id});if(seq!==state.renderSeq||id!==state.currentRepairId)return;const target=body.querySelector(".order-main")||body.querySelector(".order-layout")||body;body.querySelector("#crmFinalTools")?.remove();const wrap=document.createElement("div");wrap.innerHTML=toolHtml(d);target.appendChild(wrap.firstElementChild);bindTools(id,d);}catch(e){console.warn("crm final tools",e);}}
  async function phaseDetail(id){return api(PHASE_API,"detail",{id});}
  async function printReceipt(id,d){try{const p=await phaseDetail(id),r=d.repair||{},t=p.totals||{},items=p.items||[],client=r.customer||{},rows=items.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.quantity)}</td><td>${esc(money(x.unit_price))}</td><td>${esc(money(num(x.quantity)*num(x.unit_price)))}</td></tr>`).join("")||'<tr><td colspan="4">Позиции не указаны</td></tr>';const w=window.open("","_blank");if(!w)throw new Error("Браузер заблокировал окно печати");w.document.write(`<!doctype html><meta charset="utf-8"><title>Квитанция №${esc(r.order_no)}</title><style>body{font:14px Arial;max-width:760px;margin:30px auto;color:#111}h1{font-size:22px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left}.sum{margin-top:18px;font-size:16px}.sign{margin-top:55px;display:flex;justify-content:space-between}</style><h1>Мобильный Ангел — квитанция №${esc(r.order_no)}</h1><p><b>Клиент:</b> ${esc(client.name||"—")} · ${esc(client.phone||"—")}</p><p><b>Устройство:</b> ${esc([r.device,r.model].filter(Boolean).join(" ")||"—")} · <b>IMEI:</b> ${esc(r.imei||"—")}</p><p><b>Неисправность:</b> ${esc(r.issue||"—")}</p><p><b>Точка:</b> ${esc(r.service||"—")} · <b>Мастер:</b> ${esc(r.master||"—")}</p><table><thead><tr><th>Работа / деталь</th><th>Кол.</th><th>Цена</th><th>Сумма</th></tr></thead><tbody>${rows}</tbody></table><div class="sum"><b>Итого: ${esc(money(t.orderTotal||0))}</b><br>Оплачено: ${esc(money(t.paid||0))}<br>Осталось: ${esc(money(t.balance||0))}</div><p><b>Гарантия:</b> ${esc(r.warranty_days||0)} дней. ${esc(r.warranty_note||"")}</p><div class="sign"><span>Подпись клиента __________</span><span>Сотрудник __________</span></div><script>window.onload=()=>setTimeout(()=>window.print(),150)<\/script>`);w.document.close();}catch(e){toast(e.message||"Не удалось открыть квитанцию");}}
  function whatsapp(d){const r=d.repair||{},c=r.customer||{},digits=String(c.phone_normalized||c.phone||"").replace(/\D/g,"");if(!digits){toast("У клиента нет номера телефона");return;}const status=({accepted:"принят",diagnostics:"на диагностике",in_work:"в работе",waiting_part:"ждём запчасть",ready:"готов к выдаче",issued:"выдан"})[r.status]||r.status||"";const msg=`Здравствуйте${c.name?`, ${c.name}`:""}. Мобильный Ангел. Заказ №${r.order_no}: ${[r.device,r.model].filter(Boolean).join(" ")}. Статус: ${status}.`;window.open(`https://wa.me/${digits}?text=${encodeURIComponent(msg)}`,"_blank","noopener");}
  function fileMime(file){if(file.type)return file.type;const ext=file.name.split(".").pop()?.toLowerCase();return ext==="heic"?"image/heic":ext==="heif"?"image/heif":"";}
  function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||"").split(",").pop()||"");r.onerror=()=>reject(new Error("Не удалось прочитать файл"));r.readAsDataURL(file);});}
  async function uploadFile(id,file){if(!file)return;if(file.size>5242880){toast("Файл больше 5 МБ");return;}try{toast("Загружаем файл…");await api(FINAL_API,"upload-file",{repairId:id,fileName:file.name,mimeType:fileMime(file),base64:await fileToBase64(file)});toast("Файл добавлен");await renderRepairTools(id);}catch(e){toast(e.message||"Не удалось загрузить файл");}}
  function warrantyDialog(id){const root=document.createElement("div");root.className="final-modal";root.innerHTML='<div class="final-dialog"><h3>Гарантийное обращение</h3><p>Создаст новый заказ, связанный с исходным.</p><label>Причина обращения<input id="finalWarrantyReason" placeholder="Например, снова не работает дисплей"></label><div class="final-dialog-actions"><button class="btn btn-secondary" id="finalWarrantyCancel" type="button">Отмена</button><button class="btn btn-primary" id="finalWarrantyCreate" type="button">Создать заказ</button></div></div>';document.body.appendChild(root);$("finalWarrantyCancel")?.addEventListener("click",()=>root.remove());$("finalWarrantyCreate")?.addEventListener("click",async()=>{const reason=$("finalWarrantyReason")?.value||"";try{const d=await api(FINAL_API,"create-warranty",{id,reason});root.remove();toast(`Гарантийный заказ №${d.repair?.order_no||""} создан`);setTimeout(()=>location.reload(),700);}catch(e){toast(e.message||"Не удалось создать гарантийный заказ");}});}
  function bindTools(id,d){$("finalPrint")?.addEventListener("click",()=>printReceipt(id,d));$("finalWhatsApp")?.addEventListener("click",()=>whatsapp(d));$("finalFileInput")?.addEventListener("change",e=>uploadFile(id,e.target.files?.[0]));$("finalWarranty")?.addEventListener("click",()=>warrantyDialog(id));document.querySelectorAll("[data-final-delete-file]").forEach(b=>b.addEventListener("click",async()=>{if(!confirm("Удалить файл из заказа?"))return;try{await api(FINAL_API,"delete-file",{id:b.dataset.finalDeleteFile});toast("Файл удалён");await renderRepairTools(id);}catch(e){toast(e.message||"Не удалось удалить файл");}}));}
  function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;}
  async function mountPayroll(){if(role()!=="admin"||state.payrollMounted)return;const reports=$("reportsView");if(!reports)return;state.payrollMounted=true;const panel=document.createElement("div");panel.className="panel payroll-panel";panel.id="payrollPanel";panel.innerHTML=`<div class="payroll-head"><div><h3>Зарплаты и проценты</h3><p>Ставка + процент от валовой прибыли ремонта и продаж</p></div><div class="payroll-controls"><label>Месяц<input id="payrollMonth" type="month" value="${currentMonth()}"></label><button class="btn btn-secondary" id="payrollLoad" type="button">Показать</button></div></div><div class="payroll-table-wrap"><table class="payroll-table"><thead><tr><th>Сотрудник</th><th>Роль</th><th>Ставка</th><th>База ремонта</th><th>База продаж</th><th>Начислено</th><th></th></tr></thead><tbody id="payrollBody"><tr><td colspan="7">Загрузка…</td></tr></tbody></table></div><div class="payroll-total">Итого: <b id="payrollTotal">—</b></div>`;reports.appendChild(panel);$("payrollLoad")?.addEventListener("click",loadPayroll);await loadPayroll();}
  async function loadPayroll(){if(role()!=="admin")return;const month=$("payrollMonth")?.value||currentMonth();try{const [p,c]=await Promise.all([api(FINAL_API,"payroll",{month}),api(FINAL_API,"compensation")]),by=new Map((c.rows||[]).map(x=>[x.employee,x]));$("payrollBody").innerHTML=(p.rows||[]).map(x=>`<tr><td><b>${esc(x.employee)}</b></td><td>${x.role==="master"?"Мастер":"Менеджер"}</td><td>${esc(money(x.fixed))}</td><td>${esc(money(x.repairBase))} · ${esc(x.repairPercent)}%</td><td>${esc(money(x.salesBase))} · ${esc(x.salesPercent)}%</td><td><b>${esc(money(x.total))}</b></td><td><button class="btn btn-secondary" type="button" data-payroll-edit="${esc(x.employee)}">Настроить</button></td></tr>`).join("")||'<tr><td colspan="7">Нет сотрудников</td></tr>';$("payrollTotal").textContent=money(p.total);document.querySelectorAll("[data-payroll-edit]").forEach(b=>b.addEventListener("click",()=>compDialog(by.get(b.dataset.payrollEdit))));}catch(e){if($("payrollBody"))$("payrollBody").innerHTML=`<tr><td colspan="7">${esc(e.message||"Не удалось загрузить зарплаты")}</td></tr>`;}}
  function compDialog(row={}){const root=document.createElement("div");root.className="final-modal";root.innerHTML=`<div class="final-dialog"><h3>${esc(row.employee||"")}</h3><p>Настройка начисления за месяц.</p><label>Ставка в месяц, ₽<input id="compFixed" inputmode="decimal" value="${esc(row.fixed_monthly||0)}"></label><label>% от валовой прибыли ремонтов<input id="compRepair" inputmode="decimal" value="${esc(row.repair_percent||0)}"></label><label>% от прибыли продаж<input id="compSales" inputmode="decimal" value="${esc(row.sales_percent||0)}"></label><div class="final-dialog-actions"><button class="btn btn-secondary" id="compCancel" type="button">Отмена</button><button class="btn btn-primary" id="compSave" type="button">Сохранить</button></div></div>`;document.body.appendChild(root);$("compCancel")?.addEventListener("click",()=>root.remove());$("compSave")?.addEventListener("click",async()=>{try{await api(FINAL_API,"save-compensation",{employee:row.employee,fixedMonthly:$("compFixed").value,repairPercent:$("compRepair").value,salesPercent:$("compSales").value});root.remove();toast("Начисление сохранено");await loadPayroll();}catch(e){toast(e.message||"Не удалось сохранить");}});}
  const obs=new MutationObserver(()=>{if(state.currentRepairId&&$("repairDetailBody")?.querySelector(".order-layout")&&!$("crmFinalTools"))renderRepairTools(state.currentRepairId);if(state.actor)applyRoleUi();});obs.observe(document.documentElement,{subtree:true,childList:true});
})();