(()=>{
  "use strict";

  const BASE_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-api";
  const FINANCE_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-finance-api";
  const API_KEY="sb_publishable_tSqbw3aeAgxYuzHhQurCuw_yDze4ZNn";
  const ADMIN_SESSION_KEY="ma_schedule_admin_session_v1";
  const CRM_SESSION_KEY="ma_crm_session_v1";
  const chainedFetch=window.fetch.bind(window);
  const state={cashboxes:[],transactions:[],debts:[],profits:[],reports:null,summary:null,unassignedSales:[],loaded:false,tab:"cashboxes"};
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  const num=value=>{const n=Number(value);return Number.isFinite(n)?n:0;};
  const money=value=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(num(value))+" ₽";
  const readJson=key=>{try{return JSON.parse(localStorage.getItem(key)||"null");}catch(_){return null;}};
  const adminToken=()=>readJson(ADMIN_SESSION_KEY)?.access_token||"";
  const crmSession=()=>{try{return localStorage.getItem(CRM_SESSION_KEY)||"";}catch(_){return"";}};
  function headers(){const h={"Content-Type":"application/json","apikey":API_KEY};const a=adminToken(),s=crmSession();if(a)h.Authorization=`Bearer ${a}`;if(s)h["x-crm-session"]=s;return h;}
  function toast(message){const root=$("crmToast");if(!root)return;root.textContent=String(message||"");root.classList.add("show");setTimeout(()=>root.classList.remove("show"),3000);}
  function dateTime(value){if(!value)return"—";const d=new Date(value);if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ru-RU",{timeZone:"Europe/Moscow",day:"2-digit",month:"2-digit",year:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d);}
  function dateOnly(value){if(!value)return"—";const d=new Date(value);if(Number.isNaN(d.getTime()))return"—";return new Intl.DateTimeFormat("ru-RU",{timeZone:"Europe/Moscow",day:"2-digit",month:"2-digit",year:"numeric"}).format(d);}
  function inputDate(d){const pad=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
  function currentMonthStart(){const d=new Date();return inputDate(new Date(d.getFullYear(),d.getMonth(),1));}
  function today(){return inputDate(new Date());}
  function kindLabel(v){return({cash:"Наличные",card:"Карта",transfer:"Переводы",bank:"Счёт",safe:"Сейф",other:"Другое"})[v]||v||"—";}
  function txLabel(v){return({income:"Доход",expense:"Расход",refund:"Возврат",transfer_in:"Перевод +",transfer_out:"Перевод −"})[v]||v||"—";}
  function statusLabel(v){return({accepted:"Принят",diagnostics:"Диагностика",in_work:"В работе",waiting_part:"Ждём запчасть",ready:"Готов",issued:"Выдан"})[v]||v||"—";}

  async function api(op,payload={}){
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
    try{
      const res=await chainedFetch(FINANCE_API,{method:"POST",headers:headers(),body:JSON.stringify({op,...payload}),signal:controller.signal,cache:"no-store"});
      const data=await res.json().catch(()=>({ok:false,error:"Сервер вернул непонятный ответ"}));
      if(!res.ok||data?.ok===false)throw new Error(data?.error||`Ошибка ${res.status}`);
      return data;
    }catch(e){if(e?.name==="AbortError")throw new Error("Финансы долго не отвечают. Проверь интернет.");throw e;}finally{clearTimeout(timer);}
  }

  function salePaymentFields(){
    const form=$("saleForm");if(!form||$("financeSaleFields"))return;
    const error=$("saleFormError");
    const block=document.createElement("div");block.className="form-section finance-sale-fields";block.id="financeSaleFields";
    block.innerHTML=`<h3>Оплата</h3><div class="form-grid two"><label><span>Способ оплаты</span><select id="salePaymentMethod"><option value="cash">Наличные</option><option value="card">Карта</option><option value="transfer">Перевод</option><option value="other">Другое</option></select></label><label><span>Касса</span><select id="saleCashbox"><option value="">Определится после загрузки финансов</option></select></label></div>`;
    form.insertBefore(block,error||null);
    $("salePaymentMethod")?.addEventListener("change",populateSaleCashboxes);
    $("saleService")?.addEventListener("change",populateSaleCashboxes);
  }
  function populateSaleCashboxes(){
    const select=$("saleCashbox");if(!select)return;const service=$("saleService")?.value||"",method=$("salePaymentMethod")?.value||"cash";const kind=method==="cash"?"cash":method==="card"?"card":method==="transfer"?"transfer":"other";
    const boxes=state.cashboxes.filter(x=>x.active&&x.service===service&&x.kind===kind);select.innerHTML=boxes.length?boxes.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} · ${esc(x.service)}</option>`).join(""):'<option value="">Нет подходящей кассы</option>';
  }

  window.fetch=async function(input,init={}){
    const url=typeof input==="string"?input:input?.url||"";
    if(!url.startsWith(BASE_API)||!init?.body)return chainedFetch(input,init);
    let body=null;try{body=JSON.parse(String(init.body));}catch(_){return chainedFetch(input,init);}
    const response=await chainedFetch(input,init);
    if(!response.ok||body?.op!=="create-sale")return response;
    try{
      const data=await response.clone().json();const saleId=data?.sale?.id||"",cashboxId=$("saleCashbox")?.value||"",method=$("salePaymentMethod")?.value||"cash";
      if(saleId&&cashboxId&&adminToken())await api("assign-sale",{id:saleId,cashboxId,method});
    }catch(e){console.warn("MA CRM finance sale assignment",e);setTimeout(()=>toast("Продажа сохранена, но касса не назначена"),80);}
    return response;
  };

  function shellHtml(){return `<div class="finance-stage">
    <div class="finance-head"><div><h2>Финансы</h2><p>Кассы, платежи, расходы, долги и прибыль</p></div><div class="finance-head-actions"><button class="btn btn-secondary" id="financeRefresh" type="button">↻ Обновить</button><button class="btn btn-secondary" id="financeTransfer" type="button">↔ Перевод</button><button class="btn btn-primary" id="financeNewTx" type="button">+ Операция</button></div></div>
    <div class="finance-period"><label><span>С</span><input id="financeFrom" type="date" value="${currentMonthStart()}"></label><label><span>По</span><input id="financeTo" type="date" value="${today()}"></label><button class="btn btn-secondary" id="financeApplyPeriod" type="button">Показать</button></div>
    <div class="finance-metrics"><div class="finance-metric"><span>Денег в кассах</span><b id="finMetricCash">—</b><small>текущий расчётный остаток</small></div><div class="finance-metric"><span>Поступления</span><b id="finMetricIncome">—</b><small>за выбранный период</small></div><div class="finance-metric"><span>Расходы</span><b id="finMetricExpense">—</b><small>включая возвраты</small></div><div class="finance-metric"><span>Долги клиентов</span><b id="finMetricDebt">—</b><small>неоплаченные заказы</small></div><div class="finance-metric"><span>Опер. прибыль</span><b id="finMetricProfit">—</b><small>до неучтённых расходов</small></div></div>
    <div class="finance-tabs"><button class="active" data-fin-tab="cashboxes">Кассы</button><button data-fin-tab="operations">Операции</button><button data-fin-tab="debts">Долги</button><button data-fin-tab="profit">Прибыль</button><button data-fin-tab="reports">Отчёты</button></div>
    <div class="finance-tab-panel" id="financeTabCashboxes" data-fin-panel="cashboxes"><div class="finance-section-head"><div><h3>Кассы</h3><p>Остатки по точкам и способам оплаты</p></div><button class="btn btn-secondary" id="financeNewCashbox" type="button">+ Касса</button></div><div class="cashbox-grid" id="financeCashboxes"><div class="finance-empty">Загрузка…</div></div><div class="finance-unassigned" id="financeUnassigned"></div></div>
    <div class="finance-tab-panel hidden" id="financeTabOperations" data-fin-panel="operations"><div class="finance-section-head"><div><h3>Операции</h3><p>Оплаты ремонтов, продажи, доходы, расходы и переводы</p></div></div><div class="finance-table-wrap"><table class="finance-table"><thead><tr><th>Дата</th><th>Тип</th><th>Категория</th><th>Касса</th><th>Точка</th><th>Сотрудник</th><th>Сумма</th></tr></thead><tbody id="financeTxBody"><tr><td colspan="7" class="finance-empty">Загрузка…</td></tr></tbody></table></div></div>
    <div class="finance-tab-panel hidden" id="financeTabDebts" data-fin-panel="debts"><div class="finance-section-head"><div><h3>Долги и предоплаты</h3><p>Что клиенты ещё должны и где есть переплата</p></div></div><div class="finance-table-wrap"><table class="finance-table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Точка</th><th>Статус</th><th>Сумма</th><th>Оплачено</th><th>Остаток</th></tr></thead><tbody id="financeDebtBody"><tr><td colspan="7" class="finance-empty">Загрузка…</td></tr></tbody></table></div></div>
    <div class="finance-tab-panel hidden" id="financeTabProfit" data-fin-panel="profit"><div class="finance-section-head"><div><h3>Прибыль ремонтов</h3><p>Выручка минус себестоимость использованных запчастей</p></div></div><div class="finance-table-wrap"><table class="finance-table"><thead><tr><th>Заказ</th><th>Клиент</th><th>Точка</th><th>Мастер</th><th>Выручка</th><th>Запчасти</th><th>Валовая прибыль</th></tr></thead><tbody id="financeProfitBody"><tr><td colspan="7" class="finance-empty">Загрузка…</td></tr></tbody></table></div></div>
    <div class="finance-tab-panel hidden" id="financeTabReports" data-fin-panel="reports"><div class="finance-report-grid"><section class="finance-report-card"><h3>По точкам</h3><p>Ремонты, продажи, расходы и прибыль</p><div id="financeServiceReport"></div></section><section class="finance-report-card"><h3>По сотрудникам</h3><p>Результат по назначенным работам и продажам</p><div id="financeEmployeeReport"></div></section></div></div>
  </div>`;}

  function mountShell(){
    const view=$("paymentsView");if(!view)return;view.innerHTML=shellHtml();
    const nav=document.querySelector('.nav-item[data-view="payments"]');if(nav){nav.querySelector("span:not(.nav-icon)")?.replaceChildren(document.createTextNode("Финансы"));nav.querySelector("em")?.remove();nav.addEventListener("click",()=>{setTimeout(()=>{if($("viewTitle"))$("viewTitle").textContent="Финансы";if($("viewSubtitle"))$("viewSubtitle").textContent="Кассы, платежи, расходы и прибыль";},0);loadFinance();});}
    $("financeRefresh")?.addEventListener("click",()=>loadFinance(true));$("financeApplyPeriod")?.addEventListener("click",()=>loadFinance());$("financeNewTx")?.addEventListener("click",()=>openTransactionDialog("expense"));$("financeTransfer")?.addEventListener("click",openTransferDialog);$("financeNewCashbox")?.addEventListener("click",openCashboxDialog);
    document.querySelectorAll("[data-fin-tab]").forEach(btn=>btn.addEventListener("click",()=>switchFinanceTab(btn.dataset.finTab)));
  }
  function switchFinanceTab(tab){state.tab=tab;document.querySelectorAll("[data-fin-tab]").forEach(b=>b.classList.toggle("active",b.dataset.finTab===tab));document.querySelectorAll("[data-fin-panel]").forEach(p=>p.classList.toggle("hidden",p.dataset.finPanel!==tab));}
  function periodPayload(){const from=$("financeFrom")?.value||currentMonthStart(),to=$("financeTo")?.value||today();return {from:`${from}T00:00:00+03:00`,to:`${to}T23:59:59+03:00`};}

  function renderSummary(){const m=state.summary?.metrics||{};$("finMetricCash").textContent=money(m.cashTotal);$("finMetricIncome").textContent=money(m.income);$("finMetricExpense").textContent=money(m.expenses);$("finMetricDebt").textContent=money(m.debtTotal);$("finMetricProfit").textContent=money(m.operatingProfit);$("finMetricProfit").classList.toggle("negative",num(m.operatingProfit)<0);}
  function cashboxCard(box){return `<article class="cashbox-card"><div class="cashbox-card-top"><span class="cashbox-kind">${esc(kindLabel(box.kind))}</span><span class="cashbox-service">${esc(box.service||"Общая")}</span></div><h3>${esc(box.name)}</h3><b>${esc(money(box.balance))}</b><small>Начальный остаток: ${esc(money(box.opening_balance))}</small></article>`;}
  function renderCashboxes(){const root=$("financeCashboxes");const boxes=state.summary?.cashboxes||state.cashboxes;root.innerHTML=boxes.length?boxes.filter(x=>x.active).map(cashboxCard).join(""):'<div class="finance-empty">Касс пока нет</div>';const u=$("financeUnassigned");if(state.unassignedSales.length)u.innerHTML=`<div><b>Продажи без кассы: ${state.unassignedSales.length}</b><span>Назначьте кассу, чтобы они вошли в остатки.</span></div><button class="btn btn-secondary" id="financeAssignSales" type="button">Распределить</button>`;else u.innerHTML='<div><b>Все продажи распределены по кассам</b><span>Нераспределённых продаж нет.</span></div>';$("financeAssignSales")?.addEventListener("click",openAssignSalesDialog);}
  function renderTransactions(){const root=$("financeTxBody");root.innerHTML=state.transactions.length?state.transactions.map(x=>`<tr><td>${esc(dateTime(x.date))}</td><td><span class="fin-kind fin-${esc(x.kind)}">${esc(txLabel(x.kind))}</span></td><td><b>${esc(x.category||"—")}</b><small>${esc(x.note||"")}</small></td><td>${esc(x.cashbox?.name||"Не назначена")}</td><td>${esc(x.service||"—")}</td><td>${esc(x.employee||"—")}</td><td class="fin-amount ${num(x.amount)<0?"negative":"positive"}">${num(x.amount)<0?"−":"+"}${esc(money(Math.abs(num(x.amount))))}</td></tr>`).join(""):'<tr><td colspan="7" class="finance-empty">Операций за период нет</td></tr>';}
  function renderDebts(){const root=$("financeDebtBody");root.innerHTML=state.debts.length?state.debts.map(r=>{const e=r.economics||{},debt=num(e.balance);return `<tr><td><b>№${esc(r.order_no)}</b><small>${esc(dateOnly(r.accepted_at))}</small></td><td><b>${esc(r.customer?.name||"Без имени")}</b><small>${esc(r.customer?.phone||"")}</small></td><td>${esc(r.service||"—")}</td><td>${esc(statusLabel(r.status))}</td><td>${esc(money(e.total))}</td><td>${esc(money(e.paid))}</td><td class="fin-amount ${debt>0?"negative":"positive"}">${debt>0?"Долг ":"Переплата "+""}${esc(money(Math.abs(debt)))}</td></tr>`;}).join(""):'<tr><td colspan="7" class="finance-empty">Долгов и переплат нет</td></tr>';}
  function renderProfit(){const root=$("financeProfitBody");root.innerHTML=state.profits.length?state.profits.map(r=>{const e=r.economics||{};return `<tr><td><b>№${esc(r.order_no)}</b><small>${esc(dateOnly(r.accepted_at))}</small></td><td>${esc(r.customer?.name||"Без имени")}</td><td>${esc(r.service||"—")}</td><td>${esc(r.master||"—")}</td><td>${esc(money(e.total))}</td><td>${esc(money(e.partsCost))}</td><td class="fin-amount ${num(e.profit)<0?"negative":"positive"}">${esc(money(e.profit))}</td></tr>`;}).join(""):'<tr><td colspan="7" class="finance-empty">Ремонтов за период нет</td></tr>';}
  function renderReports(){
    const s=$("financeServiceReport"),p=$("financeEmployeeReport"),r=state.reports||{};
    s.innerHTML=(r.byService||[]).length?(r.byService||[]).map(x=>`<div class="finance-report-row"><div><b>${esc(x.service)}</b><small>Ремонты ${esc(money(x.repairRevenue))} · продажи ${esc(money(x.salesRevenue))} · расходы ${esc(money(x.expenses))}</small></div><strong class="${num(x.profit)<0?"negative":"positive"}">${esc(money(x.profit))}</strong></div>`).join(""):'<div class="finance-empty">Нет данных</div>';
    p.innerHTML=(r.byEmployee||[]).length?(r.byEmployee||[]).map(x=>`<div class="finance-report-row"><div><b>${esc(x.employee)} <span>${esc(x.role)}</span></b><small>${esc(x.orders)} операций · оборот ${esc(money(x.revenue))}</small></div><strong class="${num(x.profit)<0?"negative":"positive"}">${esc(money(x.profit))}</strong></div>`).join(""):'<div class="finance-empty">Нет данных</div>';
  }
  function renderAll(){renderSummary();renderCashboxes();renderTransactions();renderDebts();renderProfit();renderReports();populateSaleCashboxes();}

  async function loadFinance(showToast=false){
    if(!adminToken()){$("paymentsView").innerHTML='<div class="coming-soon"><div class="coming-icon">🔒</div><h2>Финансы доступны администратору</h2><p>Войдите в MA График как администратор.</p></div>';return;}
    try{
      if(!state.cashboxes.length){const boot=await api("bootstrap");state.cashboxes=boot.cashboxes||[];populateSaleCashboxes();}
      const period=periodPayload();const [summary,tx,debts,profit,reports,unassigned]=await Promise.all([api("summary",period),api("transactions",period),api("debts"),api("repair-profit",period),api("reports",period),api("unassigned-sales")]);
      state.summary=summary;state.cashboxes=summary.cashboxes||state.cashboxes;state.transactions=tx.transactions||[];state.debts=debts.rows||[];state.profits=profit.rows||[];state.reports=reports;state.unassignedSales=unassigned.sales||[];state.loaded=true;renderAll();if(showToast)toast("Финансы обновлены");
    }catch(e){toast(e.message||"Не удалось загрузить финансы");const root=$("financeCashboxes");if(root)root.innerHTML=`<div class="finance-empty">${esc(e.message||"Ошибка загрузки")}</div>`;}
  }

  function closeDialog(){document.querySelector(".fin-overlay")?.remove();document.body.style.overflow="";}
  function showDialog(inner){closeDialog();const overlay=document.createElement("div");overlay.className="fin-overlay";overlay.innerHTML=inner;overlay.addEventListener("click",e=>{if(e.target===overlay)closeDialog();});document.body.appendChild(overlay);document.body.style.overflow="hidden";overlay.querySelector(".fin-close")?.addEventListener("click",closeDialog);return overlay;}
  function cashboxOptions(selected=""){return state.cashboxes.filter(x=>x.active).map(x=>`<option value="${esc(x.id)}" ${x.id===selected?"selected":""}>${esc(x.service||"Общая")} · ${esc(x.name)}</option>`).join("");}
  function openTransactionDialog(defaultKind="expense"){
    const overlay=showDialog(`<div class="fin-dialog"><div class="fin-dialog-head"><div><h3>Новая финансовая операция</h3><p>Доход или расход, который не создаётся автоматически из заказа</p></div><button class="fin-close" type="button">×</button></div><form id="finTxForm" class="fin-form"><div class="fin-form-grid"><label><span>Тип</span><select id="finTxKind"><option value="expense">Расход</option><option value="income">Доход</option></select></label><label><span>Касса *</span><select id="finTxCashbox" required>${cashboxOptions()}</select></label><label><span>Категория *</span><input id="finTxCategory" required placeholder="Например, Аренда"></label><label><span>Сумма, ₽ *</span><input id="finTxAmount" inputmode="decimal" required placeholder="0"></label><label><span>Сотрудник / получатель</span><input id="finTxEmployee" placeholder="Необязательно"></label><label><span>Дата</span><input id="finTxDate" type="datetime-local"></label><label class="full"><span>Комментарий</span><textarea id="finTxNote" rows="2"></textarea></label></div><div class="fin-quick-cats" id="finQuickCats"></div><div class="form-error" id="finTxError"></div><div class="fin-dialog-actions"><button class="btn btn-secondary fin-close" type="button">Отмена</button><button class="btn btn-primary" type="submit">Сохранить</button></div></form></div>`);
    $("finTxKind").value=defaultKind;
    const renderCats=()=>{const cats=$("finTxKind").value==="expense"?["Аренда","Зарплата","Реклама","Коммунальные","Закупка","Доставка","Прочее"]:["Внесение владельца","Прочий доход","Возврат долга","Прочее"];$("finQuickCats").innerHTML=cats.map(c=>`<button type="button" data-cat="${esc(c)}">${esc(c)}</button>`).join("");$("finQuickCats").querySelectorAll("[data-cat]").forEach(b=>b.addEventListener("click",()=>$("finTxCategory").value=b.dataset.cat));};renderCats();$("finTxKind").addEventListener("change",renderCats);
    overlay.querySelectorAll(".fin-close").forEach(b=>b.addEventListener("click",closeDialog));$("finTxForm").addEventListener("submit",async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const occurred=$("finTxDate").value?new Date($("finTxDate").value).toISOString():null;await api("add-transaction",{kind:$("finTxKind").value,cashboxId:$("finTxCashbox").value,category:$("finTxCategory").value,amount:$("finTxAmount").value,employee:$("finTxEmployee").value,note:$("finTxNote").value,occurredAt:occurred});closeDialog();toast("Операция сохранена");await loadFinance();}catch(err){$("finTxError").textContent=err.message||"Не удалось сохранить";}finally{btn.disabled=false;}});
  }
  function openTransferDialog(){
    if(state.cashboxes.filter(x=>x.active).length<2){toast("Нужно минимум две кассы");return;}
    const overlay=showDialog(`<div class="fin-dialog small"><div class="fin-dialog-head"><div><h3>Перевод между кассами</h3><p>Перемещение денег без влияния на прибыль</p></div><button class="fin-close" type="button">×</button></div><form id="finTransferForm" class="fin-form"><div class="fin-form-grid one"><label><span>Из кассы</span><select id="finFromCashbox">${cashboxOptions()}</select></label><label><span>В кассу</span><select id="finToCashbox">${cashboxOptions()}</select></label><label><span>Сумма, ₽</span><input id="finTransferAmount" inputmode="decimal" required placeholder="0"></label><label><span>Комментарий</span><textarea id="finTransferNote" rows="2"></textarea></label></div><div class="form-error" id="finTransferError"></div><div class="fin-dialog-actions"><button class="btn btn-secondary fin-close" type="button">Отмена</button><button class="btn btn-primary" type="submit">Перевести</button></div></form></div>`);overlay.querySelectorAll(".fin-close").forEach(b=>b.addEventListener("click",closeDialog));const boxes=state.cashboxes.filter(x=>x.active);if(boxes.length>1)$("finToCashbox").value=boxes[1].id;$("finTransferForm").addEventListener("submit",async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await api("transfer",{fromCashboxId:$("finFromCashbox").value,toCashboxId:$("finToCashbox").value,amount:$("finTransferAmount").value,note:$("finTransferNote").value});closeDialog();toast("Перевод выполнен");await loadFinance();}catch(err){$("finTransferError").textContent=err.message||"Не удалось перевести";}finally{btn.disabled=false;}});
  }
  function openCashboxDialog(){
    const services=[...new Set(state.cashboxes.map(x=>x.service).filter(Boolean))];const overlay=showDialog(`<div class="fin-dialog small"><div class="fin-dialog-head"><div><h3>Новая касса</h3><p>Например, сейф или расчётный счёт</p></div><button class="fin-close" type="button">×</button></div><form id="finCashboxForm" class="fin-form"><div class="fin-form-grid one"><label><span>Название *</span><input id="finCashboxName" required placeholder="Сейф"></label><label><span>Точка</span><select id="finCashboxService"><option value="">Общая касса</option>${services.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join("")}</select></label><label><span>Тип</span><select id="finCashboxKind"><option value="cash">Наличные</option><option value="card">Карта</option><option value="transfer">Переводы</option><option value="bank">Расчётный счёт</option><option value="safe">Сейф</option><option value="other">Другое</option></select></label><label><span>Начальный остаток, ₽</span><input id="finCashboxOpening" inputmode="decimal" value="0"></label></div><div class="form-error" id="finCashboxError"></div><div class="fin-dialog-actions"><button class="btn btn-secondary fin-close" type="button">Отмена</button><button class="btn btn-primary" type="submit">Создать</button></div></form></div>`);overlay.querySelectorAll(".fin-close").forEach(b=>b.addEventListener("click",closeDialog));$("finCashboxForm").addEventListener("submit",async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await api("create-cashbox",{name:$("finCashboxName").value,service:$("finCashboxService").value,kind:$("finCashboxKind").value,openingBalance:$("finCashboxOpening").value});closeDialog();state.cashboxes=[];toast("Касса создана");await loadFinance();}catch(err){$("finCashboxError").textContent=err.message||"Не удалось создать кассу";}finally{btn.disabled=false;}});
  }
  function openAssignSalesDialog(){
    const overlay=showDialog(`<div class="fin-dialog wide"><div class="fin-dialog-head"><div><h3>Продажи без кассы</h3><p>Распределите старые продажи, чтобы остатки касс были точными</p></div><button class="fin-close" type="button">×</button></div><div class="fin-assign-list" id="finAssignList"></div></div>`);overlay.querySelectorAll(".fin-close").forEach(b=>b.addEventListener("click",closeDialog));const root=$("finAssignList");root.innerHTML=state.unassignedSales.map(s=>{const boxes=state.cashboxes.filter(x=>x.active&&(!s.service||x.service===s.service));return `<div class="fin-assign-row" data-sale-id="${esc(s.id)}"><div><b>Продажа №${esc(s.sale_no)} · ${esc([s.device,s.model].filter(Boolean).join(" "))}</b><small>${esc(s.customer?.name||"Без имени")} · ${esc(s.service||"—")} · ${esc(money(s.sale_price))}</small></div><select data-assign-method><option value="cash">Наличные</option><option value="card">Карта</option><option value="transfer">Перевод</option><option value="other">Другое</option></select><select data-assign-box>${boxes.map(x=>`<option value="${esc(x.id)}" data-kind="${esc(x.kind)}">${esc(x.name)}</option>`).join("")}</select><button class="btn btn-primary" data-assign-save type="button">Назначить</button></div>`;}).join("")||'<div class="finance-empty">Все продажи уже распределены</div>';
    root.querySelectorAll(".fin-assign-row").forEach(row=>{const method=row.querySelector("[data-assign-method]"),box=row.querySelector("[data-assign-box]"),save=row.querySelector("[data-assign-save]");const sync=()=>{const kind=method.value==="cash"?"cash":method.value==="card"?"card":method.value==="transfer"?"transfer":"other";const candidates=state.cashboxes.filter(x=>x.active&&x.service===state.unassignedSales.find(s=>s.id===row.dataset.saleId)?.service&&x.kind===kind);box.innerHTML=candidates.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join("");};method.addEventListener("change",sync);sync();save.addEventListener("click",async()=>{save.disabled=true;try{await api("assign-sale",{id:row.dataset.saleId,cashboxId:box.value,method:method.value});row.remove();toast("Продажа распределена");await loadFinance();}catch(e){toast(e.message||"Не удалось назначить кассу");}finally{save.disabled=false;}});});
  }

  salePaymentFields();mountShell();
  const main=document.querySelector("#crmMain");if(main){const observer=new MutationObserver(()=>{if(!$("paymentsView")?.classList.contains("hidden")&&!state.loaded)loadFinance();});observer.observe(main,{subtree:true,attributes:true,attributeFilter:["class"]});}
})();