(()=>{
  "use strict";
  const BASE_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-api";
  const PHASE_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-phase1-api";
  const FINAL_API="https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-crm-final-api";
  const API_KEY="sb_publishable_tSqbw3aeAgxYuzHhQurCuw_yDze4ZNn",ADMIN_SESSION_KEY="ma_schedule_admin_session_v1",CRM_SESSION_KEY="ma_crm_session_v1";
  const chainedFetch=window.fetch.bind(window),state={actor:null,currentRepairId:"",renderSeq:0,payrollMounted:false,toolsCache:new Map()};
  const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]));
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0;},money=v=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(num(v))+" ₽";
  function readJson(k){try{return JSON.parse(localStorage.getItem(k)||"null");}catch(_){return null;}}function headers(){const h={"Content-Type":"application/json","apikey":API_KEY},a=readJson(ADMIN_SESSION_KEY)?.access_token,s=localStorage.getItem(CRM_SESSION_KEY)||"";if(a)h.Authorization=`Bearer ${a}`;if(s)h["x-crm-session"]=s;return h;}
  function toast(msg){const root=$("crmToast");if(!root)return;root.textContent=String(msg||"");root.classList.add("show");setTimeout(()=>root.classList.remove("show"),2800);}
  async function api(url,op,payload={}){const r=await chainedFetch(url,{method:"POST",headers:headers(),body:JSON.stringify({op,...payload}),cache:"no-store"}),d=await r.json().catch(()=>({ok:false,error:"Некорректный ответ сервера"}));if(!r.ok||d?.ok===false)throw new Error(d?.error||`Ошибка ${r.status}`);return d;}
  function prefetchRepairTools(id){if(!id)return null;if(!state.toolsCache.has(id)){const request=api(FINAL_API,"repair-tools",{id}).catch(e=>{state.toolsCache.delete(id);throw e;});state.toolsCache.set(id,request);}return state.toolsCache.get(id);}
  function role(){return state.actor?.role|| (state.actor?.kind==="admin"?"admin":"");}
  function applyRoleUi(){const r=role(),roleText=r==="admin"?"Владелец / администратор":r==="master"?"Мастер":"Менеджер",roleEl=$("crmUserRole");document.body.dataset.crmRole=r||"";if(roleEl&&roleEl.textContent!==roleText)roleEl.textContent=roleText;const hide=(sel,on)=>document.querySelectorAll(sel).forEach(x=>x.classList.toggle("hidden",!!on));hide('[data-view="payments"]',r!=="admin");hide('[data-view="clients"],[data-view="sales"],[data-view="inventory"],[data-view="reports"]',r==="master");hide("#globalNewRepair,#mobileNewRepair",r==="master");if(r==="master"&&document.querySelector('[data-view="dashboard"]:not(.hidden)'))document.querySelector('[data-view="orders"]')?.click();mountPayroll();}
  function fastPreview(node,id){setTimeout(()=>{const body=$("repairDetailBody");if(!body||!body.querySelector(".loading-row"))return;const cells=node?.matches?.("tr[data-repair-id]")?[...node.querySelectorAll("td")]:[];const order=node?.querySelector?.(".order-number")?.textContent?.trim()||node?.querySelector?.("b")?.textContent?.trim()||`Заказ ${id}`;const device=cells.length?cells[2]?.querySelector("b")?.textContent?.trim():node?.querySelector?.("h3")?.textContent?.trim()||"";const client=cells.length?cells[1]?.querySelector("b")?.textContent?.trim():node?.querySelector?.("p b")?.textContent?.trim()||"";const phone=cells.length?cells[1]?.querySelector("small")?.textContent?.trim():"";const issue=cells.length?cells[2]?.querySelector("small")?.textContent?.trim():"";const master=cells.length?cells[4]?.textContent?.trim():node?.querySelector?.(".mobile-row-meta span")?.textContent?.trim()||"";const amount=cells.length?cells[5]?.textContent?.trim():node?.querySelector?.(".mobile-row-meta b")?.textContent?.trim()||"";const status=node?.querySelector?.(".status-badge")?.textContent?.trim()||"";if($("repairDetailTitle"))$("repairDetailTitle").textContent=order;if($("repairDetailStatus")&&status)$("repairDetailStatus").textContent=status.toUpperCase();if($("repairDetailSub")&&device)$("repairDetailSub").textContent=device;body.innerHTML=`<div class="crm-fast-preview"><div class="detail-panel"><h3>${esc(order)}</h3><div class="detail-grid"><div class="detail-item"><span>Клиент</span><b>${esc(client||"Загружаем…")}</b></div><div class="detail-item"><span>Телефон</span><b>${esc(phone||"—")}</b></div><div class="detail-item"><span>Устройство</span><b>${esc(device||"Загружаем…")}</b></div><div class="detail-item"><span>Мастер</span><b>${esc(master||"—")}</b></div>${issue?`<div class="detail-item full"><span>Неисправность</span><b>${esc(issue)}</b></div>`:""}${amount?`<div class="detail-item"><span>Сумма</span><b>${esc(amount)}</b></div>`:""}</div><div class="loading-row">Подгружаем историю, оплаты и детали заказа…</div></div></div>`;},0);}
  document.addEventListener("click",event=>{const node=event.target.closest?.("[data-repair-id],[data-recent-repair]");if(!node)return;const id=String(node.dataset.repairId||node.dataset.recentRepair||"");if(!id)return;state.currentRepairId=id;prefetchRepairTools(id);fastPreview(node,id);},true);
  function localInputIso(value){if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString();}
  async function createRepairAtomic(init,body){const payload={...body,op:"create-repair-bundle",dueAt:localInputIso($("repairDueAt")?.value||""),warrantyDays:$("repairWarrantyDays")?.value||14,warrantyNote:$("repairWarrantyNote")?.value||"",initialPayment:$("repairInitialPayment")?.value||0,initialPaymentMethod:$("repairInitialPaymentMethod")?.value||"cash"};const response=await chainedFetch(PHASE_API,{...init,method:"POST",body:JSON.stringify(payload),cache:"no-store"});if(response.ok)window.__maCrmSessionCache?.clear?.();return response;}
  async function createSaleAtomic(init,body){const payload={...body,op:"create-sale-bundle",paymentMethod:$("salePaymentMethod")?.value||"cash",cashboxId:$("saleCashbox")?.value||null};const response=await chainedFetch(PHASE_API,{...init,method:"POST",body:JSON.stringify(payload),cache:"no-store"});if(response.ok)window.__maCrmSessionCache?.clear?.();return response;}
  window.fetch=async function(input,init={}){const url=typeof input==="string"?input:input?.url||"";let body=null;try{if(init?.body)body=JSON.parse(String(init.body));}catch(_){ }
    if(url.startsWith(BASE_API)&&body?.op==="list-sales"&&role()==="master")return new Response(JSON.stringify({ok:true,sales:[]}),{status:200,headers:{"Content-Type":"application/json"}});
    if(url.startsWith(BASE_API)&&body?.op==="create-repair")return createRepairAtomic(init,body);
    if(url.startsWith(BASE_API)&&body?.op==="create-sale")return createSaleAtomic(init,body);
    const repairId=url.startsWith(BASE_API)&&body?.op==="repair"&&body?.id?String(body.id):"";if(repairId){state.currentRepairId=repairId;prefetchRepairTools(repairId);}
    const response=await chainedFetch(input,init);
    if(url.startsWith(BASE_API)&&body?.op==="bootstrap"&&response.ok){try{const d=await response.clone().json();state.actor=d?.actor||null;setTimeout(applyRoleUi,0);}catch(_){ }}
    if(repairId&&response.ok)setTimeout(()=>renderRepairTools(repairId),0);
    return response;
  };
  function sizeText(bytes){const n=num(bytes);return n<1024?`${n} Б`:n<1048576?`${(n/1024).toFixed(1)} КБ`:`${(n/1048576).toFixed(1)} МБ`;}
  function fileRows(files=[]){if(!files.length)return'<div class="final-help">Фото и файлов пока нет.</div>';return files.map(f=>`<div class="final-file"><div><b>${esc(f.file_name)}</b><small>${esc(sizeText(f.size_bytes))} · ${esc(f.uploaded_by||"")}</small></div><div class="final-file-actions">${f.url?`<a href="${esc(f.url)}" target="_blank" rel="noopener">Открыть</a>`:""}${role()!=="master"?`<button type="button" data-final-delete-file="${esc(f.id)}">Удалить</button>`:""}</div></div>`).join("");}
  function toolHtml(d){const r=d.repair||{},until=r.warranty_until?new Date(r.warranty_until):null,active=!!until&&until>=new Date();return `<div id="crmFinalTools" class="detail-panel crm-final-panel"><div class="final-title-row"><div><h3>Документы, файлы и связь с клиентом</h3><p>Финальный рабочий блок заказа</p></div>${r.warranty_case?'<span class="final-warranty-badge">Гарантийный заказ</span>':active?'<span class="final-warranty-badge active">Гарантия активна</span>':'<span class="final-warranty-badge">Гарантия не активна</span>'}</div><div class="final-actions"><button class="final-action-btn" id="finalPrint" type="button">Печать квитанции</button><button class="final-action-btn" id="finalWhatsApp" type="button">Написать в WhatsApp</button><label class="final-action-btn" style="cursor:pointer">+ Фото / файл<input id="finalFileInput" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf" hidden></label>${d.canCreateWarranty?'<button class="final-action-btn primary" id="finalWarranty" type="button">Гарантийное обращение</button>':""}</div><div class="final-files" id="finalFiles">${fileRows(d.files||[])}</div><div class="final-help">Файлы хранятся в закрытом хранилище CRM. WhatsApp открывается с уже подготовленным сообщением — отправку подтверждаешь сам.</div></div>`;}
  async function renderRepairTools(id){const body=$("repairDetailBody");if(!body||!id||!body.querySelector(".order-layout"))return;const seq=++state.renderSeq;try{const d=await prefetchRepairTools(id);state.toolsCache.delete(id);if(seq!==state.renderSeq||id!==state.currentRepairId)return;const target=body.querySelector(".order-main")||body.querySelector(".order-layout")||body;body.querySelector("#crmFinalTools")?.remove();const wrap=document.createElement("div");wrap.innerHTML=toolHtml(d);target.appendChild(wrap.firstElementChild);bindTools(id,d);}catch(e){console.warn("crm final tools",e);}}
  async function phaseDetail(id){return api(PHASE_API,"detail",{id});}
  async function printReceipt(id,d){try{const p=await phaseDetail(id),r=d.repair||{},t=p.totals||{},items=p.items||[],client=r.customer||{},rows=items.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.quantity)}</td><td>${esc(money(x.unit_price))}</td><td>${esc(money(num(x.quantity)*num(x.unit_price)))}</td></tr>`).join("")||'<tr><td colspan="4">Позиции не указаны</td></tr>';const w=window.open("","_blank");if(!w)throw new Error("Браузер заблокировал окно печати");w.document.write(`<!doctype html><meta charset="utf-8"><title>Квитанция №${esc(r.order_no)}</title><style>body{font:14px Arial;max-width:760px;margin:30px auto;color:#111}h1{font-size:22px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border-bottom:1px solid #ddd;padding:8px;text-align:left}.sum{margin-top:18px;font-size:16px}.sign{margin-top:55px;display:flex;justify-content:space-between}</style><h1>Мобильный Ангел — квитанция №${esc(r.order_no)}</h1><p><b>Клиент:</b> ${esc(client.name||"—")} · ${esc(client.phone||"—")}</p><p><b>Устройство:</b> ${esc([r.device,r.model].filter(Boolean).join(" ")||"—")} · <b>IMEI:</b> ${esc(r.imei||"—")}</p><p><b>Неисправность:</b> ${esc(r.issue||"—")}</p><p><b>Точка:</b> ${esc(r.service||"—")} · <b>Мастер:</b> ${esc(r.master||"—")}</p><table><thead><tr><th>Работа / деталь</th><th>Кол.</th><th>Цена</th><th>Сумма</th></tr></thead><tbody>${rows}</tbody></table><div class="sum"><b>Итого: ${esc(money(t.orderTotal||0))}</b><br>Оплачено: ${esc(money(t.paid||0))}<br>Осталось: ${esc(money(t.balance||0))}</div><p><b>Гарантия:</b> ${esc(r.warranty_days||0)} дней. ${esc(r.warranty_note||"")}</p><div class="sign"><span>Подпись клиента __________</span><span>Сотрудник __________</span></div><script>window.onload=()=>setTimeout(()=>window.print(),150)<\/script>`);w.document.close();}catch(e){toast(e.message||"Не удалось открыть квитанцию");}}
  function whatsapp(d){const r=d.repair||{},c=r.customer||{},digits=String(c.phone_normalized||c.phone||"").replace(/\D/g,"");if(!digits){toast("У клиента нет номера телефона");return;}const status=({accepted:"принят",diagnostics:"на диагностике",in_work:"в работе",waiting_part:"ждём запчасть",ready:"готов к выдаче",issued:"выдан"})[r.status]||r.status||"";const msg=`Здравствуйте${c.name?`, ${c.name}`:""}. Мобильный Ангел. Заказ №${r.order_no}: ${[r.device,r.model].filter(Boolean).join(" ")}. Статус: ${status}.`;window.open(`https://wa.me/${digits}?text=${encodeURIComponent(msg)}`,"_blank","noopener");}
  function fileMime(file){if(file.type)return file.type;const ext=file.name.split(".").pop()?.toLowerCase();return ext==="heic"?"image/heic":ext==="heif"?"image/heif":"";}
  function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||"").split(",").pop()||"");r.onerror=()=>reject(new Error("Не удалось прочитать файл"));r.readAsDataURL(file);});}
  async function uploadFile(id,file){if(!file)return;if(file.size>5242880){toast("Файл больше 5 МБ");return;}try{toast("Загружаем файл…");await api(FINAL_API,"upload-file",{repairId:id,fileName:file.name,mimeType:fileMime(file),base64:await fileToBase64(file)});state.toolsCache.delete(id);toast("Файл добавлен");await renderRepairTools(id);}catch(e){toast(e.message||"Не удалось загрузить файл");}}
  function warrantyDialog(id){const root=document.createElement("div");root.className="final-modal";root.innerHTML='<div class="final-dialog"><h3>Гарантийное обращение</h3><p>Создаст новый заказ, связанный с исходным.</p><label>Причина обращения<input id="finalWarrantyReason" placeholder="Например, снова не работает дисплей"></label><div class="final-dialog-actions"><button class="btn btn-secondary" id="finalWarrantyCancel" type="button">Отмена</button><button class="btn btn-primary" id="finalWarrantyCreate" type="button">Создать заказ</button></div></div>';document.body.appendChild(root);$("finalWarrantyCancel")?.addEventListener("click",()=>root.remove());$("finalWarrantyCreate")?.addEventListener("click",async()=>{const reason=$("finalWarrantyReason")?.value||"";try{const d=await api(FINAL_API,"create-warranty",{id,reason});root.remove();toast(`Гарантийный заказ №${d.repair?.order_no||""} создан`);$("closeRepairDetail")?.click();setTimeout(()=>document.querySelector('[data-view="orders"]')?.click(),80);}catch(e){toast(e.message||"Не удалось создать гарантийный заказ");}});}
  function bindTools(id,d){$("finalPrint")?.addEventListener("click",()=>printReceipt(id,d));$("finalWhatsApp")?.addEventListener("click",()=>whatsapp(d));$("finalFileInput")?.addEventListener("change",e=>uploadFile(id,e.target.files?.[0]));$("finalWarranty")?.addEventListener("click",()=>warrantyDialog(id));document.querySelectorAll("[data-final-delete-file]").forEach(b=>b.addEventListener("click",async()=>{if(!confirm("Удалить файл из заказа?"))return;try{await api(FINAL_API,"delete-file",{id:b.dataset.finalDeleteFile});state.toolsCache.delete(id);toast("Файл удалён");await renderRepairTools(id);}catch(e){toast(e.message||"Не удалось удалить файл");}}));}
  function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;}
  async function mountPayroll(){if(role()!=="admin"||state.payrollMounted)return;const reports=$("reportsView");if(!reports)return;state.payrollMounted=true;const panel=document.createElement("div");panel.className="panel payroll-panel";panel.id="payrollPanel";panel.innerHTML=`<div class="payroll-head"><div><h3>Зарплаты и проценты</h3><p>Ставка + процент от валовой прибыли ремонта и продаж</p></div><div class="payroll-controls"><label>Месяц<input id="payrollMonth" type="month" value="${currentMonth()}"></label><button class="btn btn-secondary" id="payrollLoad" type="button">Показать</button></div></div><div class="payroll-table-wrap"><table class="payroll-table"><thead><tr><th>Сотрудник</th><th>Роль</th><th>Ставка</th><th>База ремонта</th><th>База продаж</th><th>Начислено</th><th></th></tr></thead><tbody id="payrollBody"><tr><td colspan="7">Загрузка…</td></tr></tbody></table></div><div class="payroll-total">Итого: <b id="payrollTotal">—</b></div>`;reports.appendChild(panel);$("payrollLoad")?.addEventListener("click",loadPayroll);await loadPayroll();}
  async function loadPayroll(){if(role()!=="admin")return;const month=$("payrollMonth")?.value||currentMonth();try{const [p,c]=await Promise.all([api(FINAL_API,"payroll",{month}),api(FINAL_API,"compensation")]),by=new Map((c.rows||[]).map(x=>[x.employee,x]));$("payrollBody").innerHTML=(p.rows||[]).map(x=>`<tr><td><b>${esc(x.employee)}</b></td><td>${x.role==="master"?"Мастер":"Менеджер"}</td><td>${esc(money(x.fixed))}</td><td>${esc(money(x.repairBase))} · ${esc(x.repairPercent)}%</td><td>${esc(money(x.salesBase))} · ${esc(x.salesPercent)}%</td><td><b>${esc(money(x.total))}</b></td><td><button class="btn btn-secondary" type="button" data-payroll-edit="${esc(x.employee)}">Настроить</button></td></tr>`).join("")||'<tr><td colspan="7">Нет сотрудников</td></tr>';$("payrollTotal").textContent=money(p.total);document.querySelectorAll("[data-payroll-edit]").forEach(b=>b.addEventListener("click",()=>compDialog(by.get(b.dataset.payrollEdit))));}catch(e){if($("payrollBody"))$("payrollBody").innerHTML=`<tr><td colspan="7">${esc(e.message||"Не удалось загрузить зарплаты")}</td></tr>`;}}
  function compDialog(row={}){const root=document.createElement("div");root.className="final-modal";root.innerHTML=`<div class="final-dialog"><h3>${esc(row.employee||"")}</h3><p>Настройка начисления за месяц.</p><label>Ставка в месяц, ₽<input id="compFixed" inputmode="decimal" value="${esc(row.fixed_monthly||0)}"></label><label>% от валовой прибыли ремонтов<input id="compRepair" inputmode="decimal" value="${esc(row.repair_percent||0)}"></label><label>% от прибыли продаж<input id="compSales" inputmode="decimal" value="${esc(row.sales_percent||0)}"></label><div class="final-dialog-actions"><button class="btn btn-secondary" id="compCancel" type="button">Отмена</button><button class="btn btn-primary" id="compSave" type="button">Сохранить</button></div></div>`;document.body.appendChild(root);$("compCancel")?.addEventListener("click",()=>root.remove());$("compSave")?.addEventListener("click",async()=>{try{await api(FINAL_API,"save-compensation",{employee:row.employee,fixedMonthly:$("compFixed").value,repairPercent:$("compRepair").value,salesPercent:$("compSales").value});root.remove();toast("Начисление сохранено");await loadPayroll();}catch(e){toast(e.message||"Не удалось сохранить");}});}

  function installMobileUx(){
    const root=document.documentElement;
    const normalizeImei=()=>document.querySelectorAll("#repairImei,#saleImei,#detailImei").forEach(el=>{el.setAttribute("inputmode","text");el.setAttribute("autocapitalize","characters");el.setAttribute("autocomplete","off");});
    const syncViewport=()=>{const vv=window.visualViewport;if(!vv)return;root.style.setProperty("--crm-visual-height",`${Math.round(vv.height)}px`);};
    const suppressProgrammaticFocus=id=>{const el=$(id);if(!el)return;try{Object.defineProperty(el,"focus",{configurable:true,value:()=>{}});setTimeout(()=>{try{delete el.focus;}catch(_){ }},130);}catch(_){ }};
    normalizeImei();syncViewport();
    if(window.visualViewport){visualViewport.addEventListener("resize",syncViewport,{passive:true});visualViewport.addEventListener("scroll",syncViewport,{passive:true});}
    document.addEventListener("click",e=>{const open=e.target.closest?.("#globalNewRepair,#mobileNewRepair,#openSaleModal");if(!open)return;suppressProgrammaticFocus(open.id==="openSaleModal"?"salePhone":"repairPhone");setTimeout(syncViewport,80);},true);
    document.addEventListener("focusin",e=>{const el=e.target;if(!(el instanceof HTMLElement)||!el.matches("input,select,textarea"))return;if(!el.closest(".drawer,.order-modal,.dialog-card,.inv-dialog,.fin-dialog,.final-dialog"))return;setTimeout(()=>{const vv=window.visualViewport,top=(vv?.offsetTop||0)+72,bottom=(vv?.offsetTop||0)+(vv?.height||window.innerHeight)-96,r=el.getBoundingClientRect();if(r.top>=top&&r.bottom<=bottom)return;try{el.scrollIntoView({block:"nearest",behavior:"smooth"});}catch(_){el.scrollIntoView();}},140);},true);
    const obs=new MutationObserver(()=>normalizeImei());obs.observe(document.body,{subtree:true,childList:true});
  }
  installMobileUx();

  const detailRoot=$("repairDetailBody");
  if(detailRoot){const obs=new MutationObserver(()=>{if(state.currentRepairId&&detailRoot.querySelector(".order-layout")&&!$("crmFinalTools"))renderRepairTools(state.currentRepairId);});obs.observe(detailRoot,{subtree:true,childList:true});}
})();
