create table if not exists public.ma_grafik_api_audit (
  id bigint generated by default as identity primary key,
  actor_email text not null,
  action text not null check (action in ('apply_change', 'rollback')),
  work_date date,
  service text,
  before_pair jsonb,
  after_pair jsonb,
  config_before_updated_at timestamptz,
  config_after_updated_at timestamptz,
  previous_settings jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ma_grafik_api_audit_created_at_idx
  on public.ma_grafik_api_audit (created_at desc);
