-- Schedule MA Grafik shift and reminder checks without storing secrets in GitHub.
-- The cron credential is generated in PostgreSQL and never returned to clients.
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS pg_net;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM vault.secrets WHERE name = 'ma_grafik_cron_secret') THEN
    PERFORM vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'ma_grafik_cron_secret',
      'Server-to-server MA Grafik scheduled checks'
    );
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION public.ma_grafik_verify_cron_secret(p_secret text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT char_length(coalesce(p_secret, '')) = 64
     AND EXISTS (
       SELECT 1
       FROM vault.decrypted_secrets
       WHERE name = 'ma_grafik_cron_secret'
         AND decrypted_secret = p_secret
     );
$$;
REVOKE ALL ON FUNCTION public.ma_grafik_verify_cron_secret(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ma_grafik_verify_cron_secret(text) TO service_role;

CREATE TABLE IF NOT EXISTS public.ma_grafik_cron_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  executed_at timestamptz NOT NULL DEFAULT now(),
  summary jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ma_grafik_cron_runs_executed_idx
  ON public.ma_grafik_cron_runs (executed_at DESC);
ALTER TABLE public.ma_grafik_cron_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.ma_grafik_cron_runs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON public.ma_grafik_cron_runs TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Five-minute checks cover the ten-minute reminder windows.
SELECT cron.schedule(
  'ma-grafik-shift-check-every-5-minutes',
  '*/5 * * * *',
  $cron$
  SELECT net.http_post(
    url := 'https://yedzfmibceboncrytbqz.supabase.co/functions/v1/ma-shifts',
    body := '{"op":"cron-check"}'::jsonb,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret',
      (SELECT decrypted_secret
       FROM vault.decrypted_secrets
       WHERE name = 'ma_grafik_cron_secret')
    ),
    timeout_milliseconds := 15000
  );
  $cron$
);